/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;

/**
 *
 * @author krlos
 */
public class IMenu extends javax.swing.JFrame {
    private Ctrl_Reportes CTRL;
    /**
     * Creates new form IMenu
     */
    public IMenu(Ctrl_Reportes r) {
        CTRL = r;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CargarTrabajos = new javax.swing.JButton();
        CargarProfesores = new javax.swing.JButton();
        ConsultarTrabajosProfesor = new javax.swing.JButton();
        ReportarTrabajosProfesores = new javax.swing.JButton();
        ReportarTrabajosCentros = new javax.swing.JButton();
        ReportarTrabajosPostgrados = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Inicio");
        setResizable(false);

        CargarTrabajos.setText("Cargar Trabajos");
        CargarTrabajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarTrabajosActionPerformed(evt);
            }
        });

        CargarProfesores.setText("Cargar Profesores");
        CargarProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarProfesoresActionPerformed(evt);
            }
        });

        ConsultarTrabajosProfesor.setText("Consultar Trabajos");
        ConsultarTrabajosProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarTrabajosProfesorActionPerformed(evt);
            }
        });

        ReportarTrabajosProfesores.setText("Reportar Trabajos de Profesores");

        ReportarTrabajosCentros.setText("Reportar Trabajos de Centro");

        ReportarTrabajosPostgrados.setText("Reportar Trabajos de Postgrado");

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConsultarTrabajosProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(CargarProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CargarTrabajos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ReportarTrabajosProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ReportarTrabajosCentros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ReportarTrabajosPostgrados, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CargarTrabajos)
                    .addComponent(ReportarTrabajosProfesores))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CargarProfesores)
                    .addComponent(ReportarTrabajosCentros))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportarTrabajosPostgrados)
                    .addComponent(ConsultarTrabajosProfesor))
                .addGap(50, 50, 50)
                .addComponent(volver)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Cargar 
    private void CargarTrabajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarTrabajosActionPerformed
        CTRL.i_CargarTrabajos();
    }//GEN-LAST:event_CargarTrabajosActionPerformed

    private void ConsultarTrabajosProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarTrabajosProfesorActionPerformed
       CTRL.ventanaAnterior(1);
       System.out.print("ingrso a consultar en modo comision");
        CTRL.i_ConsultarTrabajos(); 
    }//GEN-LAST:event_ConsultarTrabajosProfesorActionPerformed
    //cargar profesores
    private void CargarProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarProfesoresActionPerformed
        CTRL.i_CargarProfesores();
    }//GEN-LAST:event_CargarProfesoresActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        CTRL.i_SelectUser();
    }//GEN-LAST:event_volverActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarProfesores;
    private javax.swing.JButton CargarTrabajos;
    private javax.swing.JButton ConsultarTrabajosProfesor;
    private javax.swing.JButton ReportarTrabajosCentros;
    private javax.swing.JButton ReportarTrabajosPostgrados;
    private javax.swing.JButton ReportarTrabajosProfesores;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
