/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Ctrl_Reportes;

/**
 *
 * @author krlos
 */
public class ISelectUser extends javax.swing.JFrame {
    private Ctrl_Reportes CTRL;
    /**
     * Creates new form ISelectUser
     */
    public ISelectUser(Ctrl_Reportes r) {
        CTRL = r;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Comision = new javax.swing.JButton();
        personaInteresada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Comision.setText("Comision");
        Comision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComisionActionPerformed(evt);
            }
        });

        personaInteresada.setText("Persona Interesada");
        personaInteresada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personaInteresadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(Comision))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(personaInteresada)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Comision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personaInteresada)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComisionActionPerformed
        CTRL.ventanaAnterior(1);
        CTRL.i_Menu();
    }//GEN-LAST:event_ComisionActionPerformed

    private void personaInteresadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personaInteresadaActionPerformed
        CTRL.ventanaAnterior(0);
        CTRL.i_ConsultarTrabajos();
    }//GEN-LAST:event_personaInteresadaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comision;
    private javax.swing.JButton personaInteresada;
    // End of variables declaration//GEN-END:variables
}
